CREATE DATABASE TTS_PU;
USE TTS_PU;
CREATE TABLE ODD_SEM(
SUB_CODE VARCHAR(15) PRIMARY KEY,
SUB_NAME VARCHAR(50) NOT NULL,
SUB_TYPE VARCHAR(50) NOT NULL,
COURSE_NAME VARCHAR(50) NOT NULL,
SEM_NUMBER INT NOT NULL
);
CREATE TABLE EVEN_SEM(
SUB_CODE VARCHAR(15) PRIMARY KEY,
SUB_NAME VARCHAR(50) NOT NULL,
SUB_TYPE VARCHAR(50) NOT NULL,
COURSE_NAME VARCHAR(50) NOT NULL,
SEM_NUMBER INT NOT NULL
);

